# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sc-gen CI

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: "Checkout and copy project"
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
      
    - name: npm install, and test
      if: github.event_name == 'pull_request'
      run: |
        npm install
        npm test
      
    # Publish to npm registry
    # - run: npm publish
    #   if: github.event_name == 'pull_request'
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET_NEW }}

    # Setup .npmrc file to publish to GitHub Packages
    # - uses: actions/setup-node@v2
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
  
    # # Publish to GitHub Packages
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

